### ISSUE TITLE
TimeoutError when fetch files from Hydra 

### ISSUE THREAD

**Issue by xai990** [tntech-ngin/ndn-hydra#3]
Hello,
I came across an issue when I tried to fetch the file from Hydra. 
My Hydra set up is Node 1 as client node and Node 2, Node 3, Node 4 and Node 5 as the Hydra nodes. 
I can insert the file to Hydra successfully. However, when I ran the fetch command, I had the timeout error: 
First Packet Content: /hydra/node/node4/fetch/bio.tgz
INFO:root:Timeout /hydra/node/node4/fetch/bio.tgz/seg=0
INFO:root:Timeout /hydra/node/node4/fetch/bio.tgz/seg=0
INFO:root:Timeout /hydra/node/node4/fetch/bio.tgz/seg=0
Client Fetch Command Failed.
Client finished Fetch Command! - total time (with disk): 12.0193 secs
INFO:root:Manually shutdown

Please see the screenshot for details of the error. 
![Screenshot from 2024-02-20 18-34-21](https://github.com/tntech-ngin/ndn-hydra/assets/63517862/046c6dd4-373f-4abf-8ba7-dda5f415b7a0)

Thanks,

**Comment by tntech-ngin** [comment]
Hi Xusheng,
 
I need some more information.

1. Did you create a new slice for this?  If not, please do.
2. Run everything from scratch.
3. Insert a larger file, not just 1 packet.
4. What are the routes in NFD?
5. You need at least 4 hydra nodes. It seems you have that – please confirm.
6. The replication requires some time. Please wait a few minutes before fetching. This is due to the heartbeat going out every 3 seconds or so. I can’t tell whem you are requesting these.
 
 
Can you please do these quickly and let me know as soon as possible? If you can let me know today or tomorrow, I can further debug this before our next meeting.

**Comment by tntech-ngin** [comment]
Manas mentioned publishing under a different name gets rid of this problem. And/or logout and login.

**Comment by tntech-ngin** [comment]
Please pull the updated code and see if this issue still exists/

**Comment by sankalpatimilsina12** [comment]
Added /client route from nodes back to node2. They are then able to pull file from client. This resolved the timeout issues at the client and correspondingly NACK issues at these nodes.
